spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biyesheji?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

#邮件发送配置
  mail:
    host: smtp.163.com
    username: 17626021901@163.com
    password: gengzhiqiang1
    default-encoding: UTF-8
  thymeleaf:
   cache: false

  mvc:
   view:
    prefix: /
    suffix: .html


server:
  port: 8080

#mybatis 配置


#pagehelper分页配置
pagehelper:
   helper-dialect: mysql
   reasonable: true


